version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # Добавляем HTTPS порт
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Добавляем сертификаты
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    depends_on:
      - web
      - frontend
    restart: always
    networks:
      - app-network

  web:
    build: .
    expose:
      - "8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      app-network:
        aliases:
          - backend.internal  # Специальный internal-адрес
    ports: []

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: always
    profiles:
      - dev
    networks:
      - app-network
  
  frontend:
    image: frontend:latest
    container_name: frontend
    restart: always
    build:
      context: ./a-tour_frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    networks:
      - app-network
    depends_on:
      - web

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge